Hook для правильных сообщений при коммите
banditi/chat pull request #17
Opened 2017-04-08 16:20 UTC by Nipel-Crumple

2017-04-08 16:26 UTC, sigorilla requested changes

2017-04-08 16:26 UTC, sigorilla commented on hooks/commit.js
> +log('Abort commit, specify commit message as "#{issue}: message"');
> Abort commit, specify commit message as "#{issue}: message" or "TRIVIAL: message"

2017-04-17 20:29 UTC, Nipel-Crumple commented on hooks/commit.js
> +log('Abort commit, specify commit message as "#{issue}: message"');
done

2017-04-17 20:36 UTC, sigorilla requested changes

2017-04-17 20:36 UTC, sigorilla commented on hooks/commit.js
> +log('Abort commit, specify commit message as "#{issue}: message or "TRIVIAL: message"');
Пропустил двойную ковычку после первого `message` :smile:

2017-04-17 20:49 UTC, sigorilla approved these changes

2017-04-18 15:35 UTC, merged