#4 yarn migration
banditi/chat pull request #18
Opened 2017-04-17 20:45 UTC by Nipel-Crumple

2017-04-17 20:53 UTC, sigorilla commented
А почему не стал добавлять в `.yarnrc`:

```
save-exact true
save-prefix ""
```

2017-04-17 20:55 UTC, sigorilla reviewed
Добавь в README в блок [Prerequisites](https://github.com/banditi/chat#prerequisites), что необходимо установить yarn. Хорошо бы с ссылкой на https://yarnpkg.com/en/docs/install

2017-04-17 20:57 UTC, sigorilla requested changes
Что на счет `.travis.yaml`? Там тоже надо запускать с yarn

2017-04-17 21:01 UTC, sigorilla commented
Кстати на будущее, давайте при мерже делать, во-первых, squash (благо гитхаб умеет теперь), и, во-вторых, в описании писать к коммиту писать `Close: #NN` (гитхаб умеет [закрывать таски](https://help.github.com/articles/closing-issues-via-commit-messages/))

2017-04-18 15:37 UTC, Nipel-Crumple commented
>save-exact true
save-prefix ""

Что за флаги? Есть ссыль, я не нашел, к сожалению, инфу

2017-04-19 09:23 UTC, sigorilla commented
https://yarnpkg.com/en/docs/cli/config#toc-yarn-config-list

2017-07-22 11:00 UTC, sigorilla commented
Пока висел этот PR вышел npm@5, который починил большинство проблем основных. Может переименуем этот пул реквест в "up npm"?) 

А изменения будут состоять только в `package-lock.json`, который добавится вместо `yarn.lock` и обновлении README, о том что юзайте npm>=5

2017-09-06 17:56 UTC, sigorilla commented
Нахер короче закрываю за ненадобностью 😭

2017-09-06 17:56 UTC, closed without merging