Simple model
banditi/chat pull request #26
Opened 2017-09-12 19:03 UTC by Yefim-Krokhin

### Описание

### Плюсы

### Возможные проблемы

### Связанные задачи

2017-09-12 19:24 UTC, sigorilla requested changes
По поводу настройки базы в CI: https://docs.travis-ci.com/user/database-setup#PostgreSQL

2017-09-12 19:24 UTC, sigorilla commented on package.json
> +    "pg-hstore": "2.3.2",
А что это и для чего?

2017-09-12 19:24 UTC, sigorilla commented on models/message.js
> +            type: DataTypes.DATE //TIMESTAMP WITH TIME ZONE for postgres
Комментарий ведь не соответствует действительности. Временная зона не учитывается здесь. Или учитывается?

2017-09-12 19:24 UTC, sigorilla commented on models/message.js
> +            type: DataTypes.DATE //TIMESTAMP WITH TIME ZONE for postgres
Давай писать комментарии перед строкой и без капса :) Примерно так:

```js
  // Timestamp with timezone for postgres
  type: DataTypes.DATE
```

2017-09-12 19:24 UTC, sigorilla commented on models/index.js
> +    })
Давай упростим:

```js
  // ...
  .filter((file) => file.indexOf('.') !== 0 && file !== basename && file.slice(-3) === '.js')
  // ...
```

2017-09-12 19:24 UTC, sigorilla commented on test/models/user.js
> +    it('Test user entity creation', (done) => {
should create user entity?

2017-09-12 19:27 UTC, sigorilla commented
На будущее: ветки называем `username.feature` или `username.patch-NN`, где `username` — твой ник, чтобы было понятно чья это ветка, `NN` — номер issue.

2017-09-12 19:29 UTC, sigorilla commented
И надо ещё миграцию коммитить, чтобы мы получали ту же базу

2017-09-12 19:33 UTC, Yefim-Krokhin commented on models/message.js
> +            type: DataTypes.DATE //TIMESTAMP WITH TIME ZONE for postgres
Это просто пояснение, что за хрень

2017-09-12 19:35 UTC, sigorilla commented on package.json
> +    "pg-hstore": "2.3.2",
Нашел:

> A node package for serializing and deserializing JSON data to hstore format

Давай удалять эту фигню 😄   Пока точно не нужна

2017-09-12 19:36 UTC, Yefim-Krokhin commented on package.json
> +    "pg-hstore": "2.3.2",
Интересно, неужель это я добавил? Оо

2017-09-12 20:13 UTC, sigorilla requested changes

2017-09-12 20:13 UTC, sigorilla commented on models/message.js
> +            //Timestamp with timezone for Postgres
А пробел?)

2017-09-12 20:13 UTC, sigorilla commented on README.md
> +```
Давай уберем. Это всё и так будет установлено через `npm i`

2017-09-12 20:13 UTC, sigorilla commented on test/models/user.js
> +        // drop table;
Допишем drop сразу?

2017-09-13 15:01 UTC, sigorilla approved these changes
На тесты в принципе можно и забить. Мне ок :fire:

@Nipel-Crumple посмотри тоже

2019-09-04 14:52 UTC, closed without merging